version: "3"

services:
  groupomania:
    build: .
    ports: 
      - "3000:3000"
    env_file:
      - ./.env

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-db:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-db: